website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Post, User, Comment, Like
from . import db



views = Blueprint("views", __name__)


@views.route("/")
@views.route("/home")
@login_required
def home():
    email = request.form.get('email')
    users = User.query.all()
    user = User.query.filter_by(email=email).first()
    my_post = Post.query.filter_by(user=user).all()
    count = len(my_post)
    all_posts = Post.query.all()
    return render_template('home.html', count=count, user=current_user, posts=all_posts, users=users)




@views.route("/search", methods=['GET', 'POST'])
@login_required
def search():
    username = request.form.get("username")
    user = User.query.filter_by(username=username).first()
    my_post = Post.query.filter_by(user=user).all()
    count = len(my_post)
    users = User.query.all()
    return render_template('search.html', users=users, user=current_user, count=count, title=username)



@views.route("/create-post", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post cannot be empty', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('create_post.html', user=current_user)


@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.id:
        flash('You do not have permission to delete this post.', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')

    return redirect(url_for('views.home'))


@views.route("/posts/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()

    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('views.home'))

    posts = user.posts
    return render_template("posts.html", user=current_user, posts=posts, username=username)


@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))


@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))

@views.route("/like-post/<post_id>", methods=['POST'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(
        author=current_user.id, post_id=post_id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()

    return jsonify({"likes": len(post.likes), "liked": current_user.id in map(lambda x: x.author, post.likes)})



@login_required
@views.route('/profile/<username>', methods=['GET', 'POST'])
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(user=user).order_by(Post.date_created.desc()).all()
    count = len(posts)
    return render_template('profile.html', title=username, user=user, posts=posts, count=count)





@views.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('views.home'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('views.profile', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(user.username))
    return redirect(url_for('views.profile', username=username, user=user))





@views.route('/follow/<username>', methods=['GET'])
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(user.username))
        return redirect(url_for('views.home'))
    if user == current_user:
        flash('You cannot follow yourself')
        return redirect(url_for('views.profile', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(user.username))
    return redirect(url_for('views.profile', username=username, user=user))




@views.route('/profile_update', methods=['GET', 'POST'])
def profile_update():
    if current_user.is_authenticated:
        user_details = current_user.user_variables()
        user = User.query.filter_by(id=current_user.id).first()
        if request.method == 'POST':
            updated_values_dict = request.form.to_dict()
            for k, v in updated_values_dict.items():
                if k == 'update_username':
                    user.username = v.rstrip()
                if k == 'update_password':
                    user.password = v.rstrip()
            db.session.commit()
            return redirect(url_for('views.profile_update'))
    return render_template('profile_update.html', user_details=user_details, user=current_user)

website/templates/all_posts.html
{% if posts %}
<h1 align="center" style="color:white;">{% block header %}POSTS{% endblock %}</h1>
<div id="posts">
  {% for post in posts %}
  <div class="card border-dark">
    <div class="card-header d-flex justify-content-between align-items-center">
      <b><a  style="color:black; text-decoration:none;" href="/profile/{{post.user.username}}">{{post.user.username}}</a></b>
      <div>
        <span id="likes-count-{{post.id}}">
          {{ post.likes|length }}</span> 
          {% if user.id in post.likes|map(attribute="author")|list %}
          <i
            class="fas fa-heart"
            id="like-button-{{post.id}}"
            onclick="like({{post.id}})"
          ></i>
          {% else %}
          <i
            class="far fa-heart"
            id="like-button-{{post.id}}"
            onclick="like({{post.id}})"
          ></i>
          {% endif %} 
        {% if user.id == post.author %}
        <div class="btn-group">
          <button
            type="button"
            class="btn btn-sm btn-primary dropdown-toggle"
            data-bs-toggle="dropdown"
          ></button>
          <ul class="dropdown-menu">
            <li>
              <a href="/delete-post/{{post.id}}" class="dropdown-item"
                >Delete</a
              >
            </li>
          </ul>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      <div class="card-text">{{post.text}}</div>
      <br />
      <div class="collapse" id="comments-{{post.id}}">
        <div class="card">
          <div class="card-body" id="comments-expanded-{{post.id}}">
            {% for comment in post.comments %}
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <a href="/posts/{{comment.user.username}}"
                  >{{comment.user.username}}</a
                >: {{comment.text}}
              </div>
              <div>
                <small class="text-muted"> {{comment.date_created}}</small>
                {% if user.id == comment.author or user.id == post.author %}
                <div class="btn-group">
                  <button
                    type="button"
                    class="btn btn-sm btn-primary dropdown-toggle"
                    data-bs-toggle="dropdown"
                  ></button>
                  <ul class="dropdown-menu">
                    <li>
                      <a
                        href="/delete-comment/{{comment.id}}"
                        class="dropdown-item"
                        >Delete</a
                      >
                    </li>
                  </ul>
                </div>
                {% endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <p class="card-text">
        {% if post.comments|length > 0 %}
        <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
          <small>View {{post.comments|length}} Comments</small>
        </a>
        {% else %}
        <small class="text-muted">No Comments</small>
        {% endif %}
      </p>
      <form
        class="input-group mb-3"
        method="POST"
        action="/create-comment/{{post.id}}"
      >
        <input
          type="text"
          id="text"
          name="text"
          class="form-control"
          placeholder="Comment something!"
        />
        <button type="submit" class="btn btn-primary">Comment</button>
      </form>
    </div>
    <div class="card-footer text-muted">{{post.date_created}}</div>
  </div>
  <br/ > {% endfor %}
</div>
{% endif%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script
      src="https://kit.fontawesome.com/999ca2bb93.js"
      crossorigin="anonymous"
    ></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body style="background-color:purple;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/home">Home</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="/login">Login</a>
            <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
          <div class="navbar-nav">
            <form class="nav-item nav-link" action="/search">
              <input type="text" placeholder="Search.." name="search">
              <button type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js')}}"
    ></script>
  </body>
</html>

website/templates/create_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1 style="background-color:black; color:white"  align="center">*** MAKE YOUR POST ***</h1>

<form method="POST" action="/create-post" enctype="multipart/form-data">
  <textarea name="text" id="text" class="form-control" placeholder="Create your post here..."></textarea>
  <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
  </div>
</form>
<br />
<div align="center">
  <a href="/home"
    ><button type="button" class="btn btn-lg btn-secondary">Back</button></a
  >
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}{%block content%}
{% include 'profile_all.html' %}
{% include 'all_posts.html'%}
{%endblock%}


website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form class="vh-100 gradient-custom" method="POST">
  <div class="container py-5 h-90">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-6 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 2rem;">
          <div class="card-body p-5 text-center">
            <div class="mb-md-5 mt-md-4 pb-5">
              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>

              <p class="text-white-50 mb-5">Please enter your login and password!</p>

              <label for="email">Email Address</label>
              <input
                type="text"
                id="email"
                name="email"
                class="form-control"
                placeholder="example@gmail.com"
              />

              <label for="password">Password</label>
              <input
                type="password"
                id="password"
                name="password"
                class="form-control"
                placeholder="Enter Password"
              />
            </div>
            <button class="btn btn-outline-light btn-lg px-4" type="submit">LOGIN</button>
            <div>
              <p class="mb-0">Don't have an account? <a href="/sign-up" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}


website/templates/posts.html
{% extends "posts_div.html" %} 
{% block title %}{{username}}'s Posts{% endblock
%} {% block header %} 
{{username}}'s Posts
{% endblock %} 
{% block footer %}
<div align="center">
  <a href="/home"
    ><button type="button" class="btn btn-primary btn-lg">Back</button></a
  >
</div>
{% endblock %}

website/templates/posts_div.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1>
{% include 'all_posts.html' %}
</h1>
{% endblock %}

website/templates/profile.html
{% extends 'base.html'%}

{% block content %}
<h1 style="background-color:pink;">
{% include 'profile_all.html' %}
{% include 'all_posts.html' %}
</h1>
{% endblock %}




website/templates/profile_all.html

{% block content %}

<header style="font-size: 10px;">

<div class="container" style="max-width: 93.5rem;
margin: 0 auto;
background-color:black;
padding: 0 2rem;">

	<div class="profile" style="padding: 5rem 0;">

		<div class="profile-image" style="float: left;
											 width: calc(33.333% - 1rem);
											 display: flex;
											 justify-content: center;
											 align-items: center;
											 margin-right: 3rem;">

			<img src="{{ user.avatar(150) }}" alt="" style="border-radius: 50%;">

		</div>

		<div class="profile-user-settings" style="margin-top: 1.1rem;">

				<h1 class="profile-user-name" style="display: inline-block;
												 font-size: 3rem;
												 font-weight: 300;"><a style="color:white; text-decoration:none;" href="/profile/{{user.username}}"><b>{{user.username}}</b></a></h1>
				
				{% if  current_user.is_following(user) and user.username != current_user.username %}
												 <button class="btn profile-edit-btn" style="font-weight: 600; font-size: 1.4rem;
													 line-height: 1.8;
													 border: 0.1rem solid #dbdbdb;
													 border-radius: 0.3rem;
													 padding: 0 2.4rem;
													 background-color: #008CBA;
													 margin-left: 2rem;"><a style="color:white; text-decoration:none;" href="{{url_for('views.unfollow', username=user.username)}}" class='unfollow'>Unfollow</a></button>
				
				{% elif user.username != current_user.username %}
						<button class="btn profile-edit-btn" style="font-weight: 600; font-size: 1.4rem;
							line-height: 1.8;
							border: 0.1rem solid #dbdbdb;
							border-radius: 0.3rem;
							padding: 0 2.4rem;
							background-color: #008CBA;
							margin-left: 2rem;"><a style="color:white; text-decoration:none;" href="{{url_for('views.follow', username=user.username)}}" class="follow" class="follow2" id='follow'>Follow</a></button>
				{% else %}
						<button class="btn profile-edit-btn" data-toggle="modal" data-target="#exampleModal" style="font-weight: 600; font-size: 1.4rem;
							line-height: 1.8;
							border: 0.1rem solid #dbdbdb;
							border-radius: 0.3rem;
							padding: 0 2.4rem;
							background-color: #008CBA;
							margin-left: 2rem;"> <a style="color:white; text-decoration:none;" href="{{url_for('views.create_post')}}" class='unfollow'>New Post</a></button>
							<button class="btn profile-settings-btn" aria-label="profile settings"style="font-size: 2rem;margin-left: 1rem;"><a style="color:white;" href="{{url_for('views.profile_update')}}"><i class="fas fa-cog" aria-hidden="true"></i></a></button>
				{%endif%}




			

		</div>

		<div class="profile-stats" style="margin-top: 2.3rem;">

			<ul>
				<li style="display: inline-block;font-size: 1.6rem;line-height: 1.5;margin-right: 4rem;cursor:pointer;"><a style="text-decoration:none; color:white;" href="/posts/{{user.username}}"><span class="profile-stat-count" style="font-weight: 600;" >{{count}}</span> posts</a></li>
				<li style="display: inline-block;font-size: 1.6rem;line-height: 1.5;margin-right: 4rem;cursor:pointer; color:white;"><span class="profile-stat-count" style="font-weight: 600;  color:white;" id='followers_count'>{{user.followers.count()}}</span> followers</li>
				<li style="margin-right: 0;display: inline-block;font-size: 1.6rem;line-height: 1.5;margin-right: 4rem;cursor:pointer; color:white;"><span class="profile-stat-count" style="font-weight: 600;  color:white;">{{user.followed.count()}}</span> following </li>
			</ul>
			

		</div>
	</div>

</div>
</header>

{% endblock %}





website/templates/profile_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container-sm">
    <div class="home-header">
        <form method="POST">
            <div class="card text-left">
                <div class="card-body">
                    <table class="table table-striped table-dark shadow-lg">
                        {% for key in user_details.keys() %}
                        <tr>
                            <td>{{ key }}</td>
                            <td>{{ user_details[key][1] }}</td>
                            {% if true %}
                            <td>
                                <div class="form-group">
                                    <input class="form-control" id="update_field" name="update_{{user_details[key][0]}}"
                                           placeholder="Type to update {{ key }}">
                                </div>
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Make Changes</button>
        </form>
    </div>
</div>
</div>
{% endblock %}

website/templates/search.html
{% extends "base.html"%}
{% block content %}
{% for user in users %}

{% include 'profile_all.html'%}

{% endfor %}

{% endblock %}

website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form class="vh-100 gradient-custom" method="POST">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div class="mb-md-5 mt-md-4 pb-5">
              <h2 class="fw-bold mb-2 text-uppercase">Sign Up</h2>

              <p class="text-white-50 mb-5">Please register with your details!</p>
  <div class="form-group">
    <label for="email" >Email Address</label>
    <input
      type="text"
      id="email"
      name="email"
      class="form-control"
      placeholder="example@gmail.com"
    />
    <label for="username">Username</label>
    <input
      type="text"
      id="username"
      name="username"
      class="form-control"
      placeholder="Enter Username"
    />
    <label for="password1">Password</label>
    <input
      type="password"
      id="password1"
      name="password1"
      class="form-control"
      placeholder="Enter Password"
    />
    <label for="password2">Password Again</label>
    <input
      type="password"
      id="password2"
      name="password2"
      class="form-control"
      placeholder="Enter Password Again"
    />
    <br />
    <div align="center">
      <button class="btn btn-primary" type="submit">REGISTER</button>
    </div>
  </div>
  <div>
    <p class="mb-0">Have already an account? <a href="/login" class="text-white-50 fw-bold">Login here</a>
    </p>
  </div>

</div>
</div>
</div>
</div>
</div>
</form>
{% endblock %}